name: "build"

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zenn_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: zenn

    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: ryuryu333
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build

      - run: nix develop -c zenn --version

  marp_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: marp

    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v16
        with:
          name: ryuryu333
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build

      - run: nix run .#marp -- --version
