name: "marp_build"

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  marp_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: marp

    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix build

      - run: nix run .#marp -- --version
